title: "Honghao Yu"
email: "honghao.yu.12@gmail.com"
description: "Academic personal website for research, publications, teaching, and projects."
url: "https://honghaoyu12.github.io"
baseurl: ""
timezone: "Asia/Shanghai"
markdown: kramdown
permalink: pretty

collections:
  publications:
    output: true
    permalink: /publications/:path/
  projects:
    output: true
    permalink: /projects/:path/
  talks:
    output: true
    permalink: /talks/:path/
  teaching:
    output: true
    permalink: /teaching/:path/

defaults:
  - scope:
      path: ""
    values:
      layout: page
  - scope:
      path: ""
      type: publications
    values:
      layout: item
      section: publications
  - scope:
      path: ""
      type: projects
    values:
      layout: item
      section: projects
  - scope:
      path: ""
      type: talks
    values:
      layout: item
      section: talks
  - scope:
      path: ""
      type: teaching
    values:
      layout: item
      section: teaching

author:
  name: "Honghao Yu"
  title: "Algorithmic Researcher"
  affiliation: "Your Institution"
  location: "Shenzhen, China"
  bio: "I have worked on statistical physics, in particular, phase transitions and critical dynamics. Currently, I'm working on optimization, large language models and various machine learning algorithms"
  research_interests:
    - "Interactive particle systems"
    - "Non-equilibrium phase transitions"
    - "Optimization algorithms"
  social:
    email: "honghao.yu.12@gmail.com"
    github: "yourgithub"
    scholar: "https://scholar.google.com/citations?user=QPgwKbwAAAAJ&hl=en"
    orcid: "https://orcid.org/my-orcid?orcid=0000-0002-9317-0433"
    linkedin: ""

exclude:
  - .bundle
  - .github
  - .gitignore
  - .ruby-version
  - vendor
  - node_modules
  - README.md
  - Gemfile
  - Gemfile.lock
  - academic-website-build-checklist.md
